[versions]
# libraries
junit = "4.13.2"
# Google Truth - https://github.com/google/truth/releases
truth = "1.4.5"
# Turbine - https://github.com/cashapp/turbine/releases
turbine = "1.2.1"
# Coroutines - https://github.com/Kotlin/kotlinx.coroutines/releases
coroutines = "1.11.0"
# https://github.com/ota4j-team/opentest4j/releases
opentest4j = "1.3.0"

# plugins
changelog = "2.5.0"
# https://github.com/JetBrains/compose-multiplatform/releases
compose = "1.10.3"
# https://github.com/JetBrains/intellij-platform-gradle-plugin/releases
intellij-platform = "2.16.0"
kotlin = "2.3.21"
kover = "0.9.8"
# https://github.com/brian-mcnamara/plugin_uploader/releases
plugin-uploader = "1.3.5"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
intellij-platform = { id = "org.jetbrains.intellij.platform", version.ref = "intellij-platform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
plugin-uploader = { id = "dev.bmac.intellij.plugin-uploader", version.ref = "plugin-uploader" }